### ISSUE TITLE
Add src/types/types.d.ts

### ISSUE THREAD

**Issue by JSneak** [dictyBase/dicty-frontpage#1039]
## Steps to implement:
- [x] Research whether it's best practice to have one massive global library vs a bunch of smaller ones
- [ ] Create global library dictyFrontPage
- [ ] Add types to the library

**Comment by JSneak** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types

**Comment by JSneak** [comment]
https://stackoverflow.com/questions/42233987/how-to-configure-custom-global-interfaces-d-ts-files-for-typescript

**Comment by JSneak** [comment]
Setup details:
1. create src/types/global.d.ts
2. edit the tsconfig.json to add` "typeRoots": ["./src/types/global"],`

**Comment by cybersiddhu** [comment]
Another explanation
https://stackoverflow.com/questions/30357634/how-do-i-use-namespaces-with-typescript-external-modules

**Comment by cybersiddhu** [comment]
> Setup details:
> 
>     1. create src/types/global.d.ts
> 
>     2. edit the tsconfig.json to add` "typeRoots": ["./src/types/global"],`

It seems though i was kind of looking for a automated globally available type definitions, they are frowned upon. So, instead we can just create a project wise `.ts` file, export types under certain namespace and import them in the component as necessary. It will keep things in one central place however following the recommended practice.

In `src/types/DictyFrontPage.ts`
```js
export namespace DictyFrontPage {
    export interface PaperProps {}
    export interface AppBarProps {]
}

// add more namespaces and interfaces as necessary
```

Then you can import them in the module
```js
import {DictyFrontPage} from "./src/types/DictyFrontPage"
```

+ Use `namespaces` for grouping multiple definitions. 
+ You can also directly export the types without grouping in a namespaces if that seems more intuitive.
