### ISSUE TITLE
Add table width / size  and line editing

### ISSUE THREAD

**Issue by pfey03** [dictyBase/dicty-frontpage#121]
To make a box I did a one cell table. But cannot edit width or the stroke to make it more stand out
https://testdb.dictybase.org/techniques/growth

**Comment by pfey03** [comment]
Or add a new tool to add a box that can be sized and also filled with a color

**Comment by pfey03** [comment]
And add a line tool

**Comment by wildlifehexagon** [comment]
moved to #155
