### ISSUE TITLE
line spacing tool

### ISSUE THREAD

**Issue by pfey03** [dictyBase/dicty-frontpage#128]
We sometimes need text more dense in Fig. captions etc.

Please add line spacing so  we can pack lines flexibly

**Comment by wildlifehexagon** [comment]
Icon for this: https://material.io/tools/icons/?icon=format_line_spacing&style=baseline

**Comment by wildlifehexagon** [comment]
sandbox of possible implementation: https://codesandbox.io/s/7zo5rv17vj
