### ISSUE TITLE
HR divider cannot be deleted

### ISSUE THREAD

**Issue by pfey03** [dictyBase/dicty-frontpage#132]
I noticed there is now an HR divider. However, I adde one and the saved the doc to continue later and I cannot edit below and cannot get rid of the HR line. I can only add content above the line
https://testdb.dictybase.org/research/techniques/transformations

**Comment by wildlifehexagon** [comment]
<hr> dividers can be deleted by either putting the cursor on the line above the divider and hitting `delete` or by putting the cursor below the divider and hitting `backspace`.

I was able to do so on the provided page without issue. Let me know if you are still having problems.

Also, I will be providing an updated version of the divider in the next release. It will behave in the same way but will follow our Material-UI guidelines.
