### ISSUE TITLE
Comprehensive List editing not possible

### ISSUE THREAD

**Issue by pfey03** [dictyBase/dicty-frontpage#133]
I had to afdd complicated lists with sublists etc. But formatting is not consistent, and last item is not continuously numbered but has number 1. These numbers and stuff needs to be more editable.
https://testdb.dictybase.org/research/techniques/transformations

**Comment by wildlifehexagon** [comment]
Specific notes on issues with the page listed above:

Under Calcium phosphate precipitation: The second sublist has an extra dark dot and the next point restarted with 1 and couldn't do 10.
Under A. Selection of Transformants in liquid media after the Optional stuff it restarted with 1. everything that looks ok was a lot of work. we basically need the ability to fix numbers in lists we need all flexibility
