### ISSUE TITLE
Component for displaying news

### ISSUE THREAD

**Issue by cybersiddhu** [dictyBase/dicty-frontpage#2]
Features...

* Should be a dumb(presentational) component.
* Accept a list of new through props.
* Expect to produce an unordered list.
* Possible shape of the data
```
[{"date":  "date",  "news": "blah blah blah...", "source": "Dicty stock center"}, {.....}]
```
* Document props using [styleguidist](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#getting-started-with-styleguidist) - Helpful for collaborative development.
* Validate props using [flow](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-flow)
* Unit tests using `jest`, probably needed to add [enzyme](https://github.com/airbnb/enzyme) as described [here](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#testing-components).
* Migrate css from previous angular project and use them with `styled-components`. This will probably be most of the work.

**Comment by cybersiddhu** [comment]
#1

**Comment by agilgur** [comment]
* Created a News component that accepts a list of news through props
* Hard-coded the news data in App.js for now
* Installed styleguidist and flow
* Need to run unit test
* Need to style the component properly

**Comment by cybersiddhu** [comment]
Now separate all of the bullet points into their separate small issues and link them back to here as i did with the flow related issue.
Then finish them one by one.
