### ISSUE TITLE
Make 'About' page editable with DraftJS

### ISSUE THREAD

**Issue by agcpbg** [dictyBase/dicty-frontpage#28]
- make Technical Summary and Special Thanks editable with DraftJS
- figure out a way to do the conversion of html to JSON for Draftjs

**Comment by cybersiddhu** [comment]
* Migrate state management to redux

**Comment by agcpbg** [comment]
When implementing the toolbar plugin, I ran into a lot of errors related to trying to use the same plugin instance with different editors.  Here are some potential solutions I found heplful:

- [https://github.com/draft-js-plugins/draft-js-plugins/blob/master/FAQ.md#can-i-use-the-same-plugin-for-multiple-plugin-editors](url)

- [https://github.com/draft-js-plugins/draft-js-plugins/issues/298](url)
Actually we found a way that works. Ended up creating a new plugin instance within the constructor of the component and assigned it to a property of the component. Then we were able to grab the MentionSuggestions component from that to render the list. This resolved the issue of iterating numerous instances of this component on our page:

  // MentionsComponent.jsx
  ...
  constructor(props) {
    super(props);

    this._mentionPlugin = createMentionPlugin();
  }

  render() {
    const { MentionSuggestions } = this._mentionPlugin;

    return (
      <div>
       ...
        <MentionSuggestions
          onSearchChange={ this.onSearchChange }
          suggestions={ this.state.suggestions }
        />
      </div>
    );
  }

**Comment by agcpbg** [comment]
The draft-js-richbuttons-plugin is now working for the toolbar buttons.  The blockstyle buttons seem to require an extra click to get them to work properly and the styling needs to be done.  These are items to revisit.

**Comment by cybersiddhu** [comment]
Try to use [slate](https://github.com/ianstormtaylor/slate/) for editor

**Comment by wildlifehexagon** [comment]
I've started working on finishing this in `feature/about-slate-with-refactoring`. Still to do:

- [ ] Finish adding toolbar buttons (see [beta page](https://betatest.dictybase.org/stockcenter/orders/information) for full list)
- [ ] Refactor into multiple components (i.e. toolbar, editor, etc)
- [ ] Add save/cancel buttons
- [ ] Implement Redux (could be its own issue)
- [ ] Clean up Draft.js references and remove packages
- [ ] Add both components/editors to About page
- [ ] Write documentation/tests/Flow

**Comment by wildlifehexagon** [comment]
About page is now editable in `develop`, just needs to have Redux implemented (will be worked on in `refactor/add-redux` branch)
