### ISSUE TITLE
Adding flow type checking for news component

### ISSUE THREAD

**Issue by cybersiddhu** [dictyBase/dicty-frontpage#3]
The setup is more or less described [here](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-flow)

The guide is [here](https://flow.org/en/docs/frameworks/react/).
You also have to install [flow-typed](https://github.com/flowtype/flow-typed) to have the type checks working with 3rd party libraries. 

#2 
#1

**Comment by agilgur** [comment]
I installed flow and flow-typed... but when I run flow (npm run flow), I get this message:

... 153 more errors (only 50 out of 203 errors displayed)
To see all errors, re-run Flow with --show-all-errors
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! dicty-frontpage@0.1.0 flow: `flow`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the dicty-frontpage@0.1.0 flow script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alinagilgur/.npm/_logs/2017-07-14T14_29_06_011Z-debug.log

**Comment by agilgur** [comment]
The problem has been fixed. Flow runs properly now.
