### ISSUE TITLE
Adding prettier to format code automatically

### ISSUE THREAD

**Issue by agilgur** [dictyBase/dicty-frontpage#5]
#2

**Comment by cybersiddhu** [comment]
Standard command line:
```
prettier --no-semi --trailing-comma all --jsx-bracket-same-line true
```

**Comment by agilgur** [comment]
When I run this command (npm run prettier ...), I get this error:

npm ERR! missing script: prettier

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alinagilgur/.npm/_logs/2017-07-14T14_46_49_698Z-debug.log

**Comment by agilgur** [comment]
The problem has been solved. Prettier formatting has been added to the code.
