### ISSUE TITLE
Broken deployment

### ISSUE THREAD

**Issue by cybersiddhu** [dictyBase/dicty-frontpage#53]
The build from the develop branch is broken, the primary bundle file throws a runtime error. 
However, it runs the developmental server. So, go ahead a fix the error and use this issue to write the diagnosis for it.

**Comment by wildlifehexagon** [comment]
There was an issue with the static server's handling of the root path. That has since been fixed, and the Dockerfiles have been updated accordingly to remove the unnecessary `vf` and `sub-url` arguments. Beta site is now live.
