### ISSUE TITLE
Update color scheme

### ISSUE THREAD

**Issue by wildlifehexagon** [dictyBase/dicty-frontpage#73]
Let's use this issue for color scheme ideas.

**Comment by pfey03** [comment]
#002080  Dark: header, footer, and dark blue elsewhere 
#3366ff  Medium
#99b3ff  Light
#ccd9ff  Very light

or here a slightly more 'green'
#004080
#0073e6
#80c1ff
#cce6ff

**Comment by pfey03** [comment]
For both color regimes above, the medium is a very strong blue and should be used sparingly. The others (dark and light, very light) are easier on the eye in both cases

**Comment by pfey03** [comment]
Try the top one on the front page and lets see how it looks. If you need one more shade in a row (5 total, let me know and I recreate them anew

**Comment by wildlifehexagon** [comment]
Per our discussion today, we have decided to use the second set of colors throughout all of our applications. I will be releasing a new version of the header-footer to reflect this.

**Comment by wildlifehexagon** [comment]
More comprehensive color scheme:

#004080 (darkest, used in header and footer)
#0059b3 (halfway point between this and medium, which is kind of bright)
#0073e6 (medium)
#3399ff
#80c1ff
#cce6ff
#e6f2ff (lightest)

**Comment by wildlifehexagon** [comment]
I have been updating all of our web apps to use the new color scheme. All of the updated versions are in `feat/new-colors` branches. The only one that still needs to be done is DSC -- I will post a note when all versions are updated and their release versions.

**Comment by wildlifehexagon** [comment]
DSC has also been updated -- will set out a release schedule for all apps next week.

**Comment by wildlifehexagon** [comment]
I've posted the color scheme inside our new [frontend development guide](https://github.com/dictybase-playground/dev-notes/blob/master/frontend.md).

Will close this issue, but it can still be used for any further discussion.
