### ISSUE TITLE
Change button colors on homepage

### ISSUE THREAD

**Issue by wildlifehexagon** [dictyBase/dicty-frontpage#83]
Let's make the medium blue like the mouse-over blue and the mouse over blue even a bit lighter.

**Comment by pfey03** [comment]
Yeah, the dark blue with that blue of mouse over would look decent and lighter mouse over is ok as well.

I think the font could also be a notch bigger?

**Comment by pfey03** [comment]
Maybe use the top colors from here https://github.com/dictyBase/dicty-frontpage/issues/73

**Comment by wildlifehexagon** [comment]
`testdb` has been updated with some new button colors. I stuck with the original suggestion of changing the medium blue to the mouse-over blue, and I increased the font size.

I tried the top colors from #73 initially but they were too bright. I think the new changes are an improvement but maybe we can go over both sets of colors in person next week to verify.

**Comment by pfey03** [comment]
Yes, this is better. Once the tables on the right are replaced it will look even nicer. This section with the annotation numbers I would totally re-design. I can create a mockup one of these days.
