### ISSUE TITLE
inline editing options/tools

### ISSUE THREAD

**Issue by pfey03** [dictyBase/dicty-frontpage#84]
I need the following editing tools to seriously start adding web content on static pages.

- Add 2 fonts. 
**Default font.** I think we should have one Default font for all pages. 
**Monospaced font.** For certain genomic and table content, a font like Curier would be useful. 
- Font sizes. For example, we sometimes need to add a reference and want to use a smaller font size to set it apart.
- Font colors. For full page creation, we should be able to choose a color to highlight something.

**Comment by pfey03** [comment]
Oh I also nee to be able add files, for examples PDF files (most important)

Thanks!

**Comment by wildlifehexagon** [comment]
Closing this since these issues are now covered:

Font families and sizes are in the editor. Color picker is in next release. We will be discussing file uploads next week (uploading PDFs will be done similarly to images).
