### ISSUE TITLE
Document json format for download page

### ISSUE THREAD

**Issue by cybersiddhu** [dictyBase/dicty-frontpage#85]
Preferably generate in swagger format as we have for [dictybase-api](https://dictybase.github.io/dictybase-api/). The structured json files need to be committed [here](https://github.com/dictyBase/dictybase-api/tree/master/docs).

**Comment by wildlifehexagon** [comment]
The downloads swagger file has been committed and added to [dictybase-api](https://dictybase.github.io/dictybase-api/)
