### ISSUE TITLE
use of dispatch

### ISSUE THREAD

**Issue by cybersiddhu** [dictyBase/dicty-frontpage#86]
https://github.com/dictyBase/dicty-frontpage/blob/1f88f9c347852d4f899da7d589900a0c49e76901/src/actions/downloads.js#L41

The `dispatch` is not needed for sync action. So, instead could you simply reduce that to a single function call.

**Comment by wildlifehexagon** [comment]
fixed in 2113b3c49ac724e0d481e2d5dc80c5cc6f803e5f
