### ISSUE TITLE
Delete Upcoming Meetings page from Community dropdown

### ISSUE THREAD

**Issue by pfey03** [dictyBase/dicty-frontpage#88]
The Upcoming Meetings was David's idea. But it would be much work for us if we want to anticipate what meetings our researchers go to and list them here
https://testdb.dictybase.org/community/meetings

The only option I see is, making it a Community editable page where everyone can list the Meeting they are interested in. But we would need to know if people would like that. 

For now, just remove.

**Comment by wildlifehexagon** [comment]
I have removed this from the navbar and footer.
